apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
components:
- ../../../../../kustomize/components/network-policies
- ../../../../../kustomize/components/cymbal-branding
patches:
- path: patches/frontend-service.yaml
